#!/bin/sh /etc/cms.common

START=90
STOP=10
USE_PROCD=1

PROG=/rwdata/opt/rtor_obu_warning/v2x_rtor_obu_warning_exec
CONF=/rwdata/opt/rtor_obu_warning/rtor_obu_warning_config.json
HOST=127.0.0.1
PORT=43985

start_service() {
    procd_open_instance
    procd_set_param command "${PROG}" "${HOST}" "${CONF}" "${PORT}"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}